server:
  port: 8989
  servlet:
    context-path: /admin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_hibernate?serverTimezone=Europe/Moscow
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  thymeleaf:
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
