server:
  port: 8987
  servlet:
    context-path: /admin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_food_shop_db?createDatabaseIfNotExist=true&&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  thymeleaf:
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

picture:
  storage:
    path: C:\Users\EVA\IdeaProjects\study-food-shop\pictures
    type: file



